"""
Flow Matching Centerline Head
基于Flow Matching + GRPO的中心线生成头

替代原有的DiffusionCenterlineHead
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import copy
import cv2
import os

from mmdet.models import HEADS, build_loss
from mmcv.runner import force_fp32
from mmcv.cnn import Linear, bias_init_with_prob

from ..modules.flow_matching import (
    FlowMatchingModule,
    FlowVelocityNet,
    FlowMatchingLoss,
)
from ..modules.grpo import GRPO, CenterlineReward
from ..modules.matcher import HungarianMatcher
from ..modules.utils import (
    fit_bezier,
    resample_polyline,
    bezier_interpolate,
    normalize_coords,
    denormalize_coords,
)

# 从原始CGNet导入GNN和TopologyHead
from ...cgnet.dense_heads.CGNet_head import GNN, TopologyHead as CGNetTopologyHead, GRU


@HEADS.register_module()
class FlowCenterlineHead(nn.Module):
    """
    Flow Matching中心线检测头
    
    核心设计:
    1. Flow Matching生成几何 (节点坐标)
    2. MLP预测拓扑 (邻接矩阵)
    3. GRPO优化整体质量
    """
    
    def __init__(self,
                 num_classes=1,
                 embed_dims=256,
                 num_queries=50,
                 num_pts_per_line=20,
                 num_ctrl_points=4,
                 coord_mode='ctrl_points',
                 num_flow_layers=4,
                 num_gnn_layers=6,
                 num_sampling_steps=1,
                 flow_recon_weight=0.0,
                 flow_time_sampling='uniform',
                 flow_time_beta_a=1.0,
                 flow_time_beta_b=1.0,
                 flow_time_clip_eps=1e-4,
                 flow_time_weighting='none',
                 flow_time_weight_power=2.0,
                 flow_time_weight_lambda=2.0,
                 flow_coord_scaling='none',
                 x0_prior_type='bezier',
                 x0_residual_scale=0.05,
                 coord_min=0.01,
                 coord_max=0.99,
                 pc_range=[-15.0, -30.0, -5.0, 15.0, 30.0, 3.0],
                 bev_h=200,
                 bev_w=100,
                 use_grpo=True,
                 grpo_samples=8,
                 grpo_start_epoch=12,
                 transformer=None,
                 positional_encoding=None,
                 query_embed_type='all_pts',
                 loss_cls=dict(type='FocalLoss', use_sigmoid=True, loss_weight=2.0),
                 loss_flow_weight=5.0,
                 loss_topo_weight=1.0,
                 use_jaq=True,
                 loss_kp_weight=1.0,
                 dilate_radius=3,
                 bbox_coder=None,
                 train_cfg=None,
                 test_cfg=None):
        super().__init__()
        
        self.num_classes = num_classes
        self.embed_dims = embed_dims
        self.num_queries = num_queries
        self.num_pts_per_line = num_pts_per_line
        self.num_ctrl_points = num_ctrl_points
        self.coord_mode = coord_mode
        if self.coord_mode not in ('ctrl_points', 'points'):
            raise ValueError(f'Unsupported coord_mode={self.coord_mode!r}, expected "ctrl_points" or "points".')
        # Number of points generated by Flow Matching.
        # - ctrl_points: generate Bézier control points (P=num_ctrl_points), then interpolate to num_pts_per_line.
        # - points: generate fixed sampled polyline points directly (P=num_pts_per_line).
        self.flow_num_points = self.num_ctrl_points if self.coord_mode == 'ctrl_points' else self.num_pts_per_line
        self.num_sampling_steps = num_sampling_steps
        self.flow_recon_weight = flow_recon_weight
        self.flow_time_sampling = flow_time_sampling
        self.flow_time_beta_a = flow_time_beta_a
        self.flow_time_beta_b = flow_time_beta_b
        self.flow_time_clip_eps = flow_time_clip_eps
        self.flow_time_weighting = flow_time_weighting
        self.flow_time_weight_power = flow_time_weight_power
        self.flow_time_weight_lambda = flow_time_weight_lambda
        self.flow_coord_scaling = flow_coord_scaling

        self.x0_prior_type = x0_prior_type
        self.x0_residual_scale = x0_residual_scale
        self.coord_min = float(coord_min)
        self.coord_max = float(coord_max)
        if not (0.0 <= self.coord_min < self.coord_max <= 1.0):
            raise ValueError(f'coord_min/coord_max must satisfy 0<=min<max<=1, got {self.coord_min}, {self.coord_max}.')

        if self.coord_mode == 'ctrl_points':
            # ctrl_points mode always uses control points as prior.
            self.x0_prior_type = 'ctrl_points'
        else:
            if self.x0_prior_type not in ('bezier', 'points', 'bezier_residual'):
                raise ValueError(
                    f'Unsupported x0_prior_type={self.x0_prior_type!r} for coord_mode="points"; '
                    'expected "bezier|points|bezier_residual".'
                )
        self.pc_range = pc_range
        self.bev_h = bev_h
        self.bev_w = bev_w
        self.use_grpo = use_grpo
        self.grpo_samples = grpo_samples
        self.grpo_start_epoch = grpo_start_epoch
        self.loss_flow_weight = loss_flow_weight
        self.loss_topo_weight = loss_topo_weight
        self.use_jaq = use_jaq
        self.loss_kp_weight = loss_kp_weight
        self.dilate_radius = dilate_radius
        self.train_cfg = train_cfg
        self.test_cfg = test_cfg
        
        self.real_w = pc_range[3] - pc_range[0]
        self.real_h = pc_range[4] - pc_range[1]
        self.num_gnn_layers = num_gnn_layers
        self.query_embed_type = query_embed_type
        
        # ===== Transformer (CGNet风格) =====
        if transformer is not None:
            from mmcv.utils import build_from_cfg
            from mmdet.models.utils.builder import TRANSFORMER
            self.transformer = build_from_cfg(transformer, TRANSFORMER)
            self.bev_encoder_type = transformer['encoder']['type']
        else:
            self.transformer = None
            self.bev_encoder_type = None
        
        # BEV Embedding (for BEVFormer-style encoding)
        if self.bev_encoder_type == 'BEVFormerEncoder':
            self.bev_embedding = nn.Embedding(bev_h * bev_w, embed_dims)
        else:
            self.bev_embedding = None
        
        # Positional Encoding
        if positional_encoding is not None:
            from mmcv.cnn.bricks.transformer import build_positional_encoding
            self.positional_encoding = build_positional_encoding(positional_encoding)
        else:
            self.positional_encoding = None
        
        # ===== 核心模块 =====
        # Flow Matching
        self.flow_module = FlowMatchingModule(embed_dims)
        self.velocity_net = FlowVelocityNet(
            d_model=embed_dims,
            num_layers=num_flow_layers,
        )
        self.flow_loss = FlowMatchingLoss(
            recon_loss_weight=flow_recon_weight,
            time_sampling=flow_time_sampling,
            time_beta_a=flow_time_beta_a,
            time_beta_b=flow_time_beta_b,
            time_clip_eps=flow_time_clip_eps,
            time_weighting=flow_time_weighting,
            time_weight_power=flow_time_weight_power,
            time_weight_lambda=flow_time_weight_lambda,
            coord_scale=self._build_flow_coord_scale(pc_range, flow_coord_scaling),
        )
        
        # 动态位置先验预测器 (从query特征预测初始位置，解决Hungarian匹配不对齐问题)
        # 输入: [B, N, D] query_feat_per_line
        # 输出: [B, N, P, 2] 初始位置 (归一化到[0,1])
        self.x0_predictor = nn.Sequential(
            nn.Linear(embed_dims, embed_dims),
            nn.ReLU(inplace=True),
            nn.Linear(embed_dims, num_ctrl_points * 2),
        )

        # Optional: points-mode prior/residual predictors.
        # They are no-ops unless coord_mode='points' and x0_prior_type requests them.
        self.x0_points_predictor = nn.Sequential(
            nn.Linear(embed_dims, embed_dims),
            nn.ReLU(inplace=True),
            nn.Linear(embed_dims, 2),
        )
        self.x0_residual_predictor = nn.Sequential(
            nn.Linear(embed_dims, embed_dims),
            nn.ReLU(inplace=True),
            nn.Linear(embed_dims, 2),
        )
        
        # 存在性分类头 (CGNet风格)
        cls_branch = []
        for _ in range(2):
            cls_branch.append(nn.Linear(embed_dims, embed_dims))
            cls_branch.append(nn.LayerNorm(embed_dims))
            cls_branch.append(nn.ReLU(inplace=True))
        cls_branch.append(nn.Linear(embed_dims, 1))
        self.cls_head = nn.Sequential(*cls_branch)
        
        # 拓扑预测 - 使用原始CGNet的GNN + TopologyHead + GRU (多层迭代)
        self.vertex_gnn = GNN(
            embed_dims=embed_dims,
            feedforward_channels=embed_dims * 2,
            num_fcs=2,
            ffn_drop=0.1,
            edge_weight=0.8,
        )
        self.vertex_gru = GRU(embed_dims, embed_dims)
        self.topo_head = CGNetTopologyHead(embed_dims, activate=True)  # 返回sigmoid后的结果
        
        # 多层监督的拓扑头 (CGNet风格)
        self.topo_heads_multi = nn.ModuleList([
            CGNetTopologyHead(embed_dims, activate=False) for _ in range(num_gnn_layers)
        ])
        
        # Learnable Query Embedding (CGNet风格)
        if query_embed_type == 'all_pts':
            self.query_embedding = nn.Embedding(num_queries, embed_dims * 2)
            self.actual_num_queries = num_queries
            self.num_instances = num_queries  # 每个query是一条线
        elif query_embed_type == 'instance_pts':
            # instance_pts: each line has `flow_num_points` point-queries (ctrl_points mode: P=num_ctrl_points;
            # points mode: P=num_pts_per_line).
            self.num_instances = num_queries  # 线的数量
            self.instance_embedding = nn.Embedding(num_queries, embed_dims * 2)
            self.pts_embedding = nn.Embedding(self.flow_num_points, embed_dims * 2)
            self.query_embedding = None
            # 实际query数量 = num_instances * flow_num_points
            self.actual_num_queries = num_queries * self.flow_num_points
        else:
            self.query_embedding = nn.Embedding(num_queries, embed_dims * 2)
            self.actual_num_queries = num_queries
            self.num_instances = num_queries
        
        # GRPO
        if use_grpo:
            self.grpo = GRPO(num_samples=grpo_samples)
        
        # ===== JAQ (Junction-Aware Query) =====
        if use_jaq:
            # BEV keypoint prediction head (CGNet style)
            self.kp_decoder = nn.Sequential(
                nn.Conv2d(embed_dims, embed_dims, 3, 1, 1, bias=False),
                nn.BatchNorm2d(embed_dims),
                nn.ReLU(inplace=True),
                nn.Conv2d(embed_dims, embed_dims, 3, 1, 1, bias=False),
                nn.BatchNorm2d(embed_dims),
                nn.ReLU(inplace=True),
            )
            self.kp_proj = nn.Sequential(
                nn.Conv2d(embed_dims, 1, 1),
                nn.Sigmoid()
            )
        
        # 损失函数
        self.loss_cls_fn = build_loss(loss_cls)
        
        # Hungarian匹配器
        self.matcher = HungarianMatcher(
            cost_class=1.0,
            cost_bezier=5.0,
            cost_chamfer=0.0,
        )
        
        # bbox_coder (CGNet风格后处理)
        if bbox_coder is not None:
            from mmdet.core import build_bbox_coder
            self.bbox_coder = build_bbox_coder(bbox_coder)
        else:
            self.bbox_coder = None
        
        # 当前epoch (由hook设置)
        self.current_epoch = 0

    @staticmethod
    def _build_flow_coord_scale(pc_range, flow_coord_scaling):
        """
        Build per-dimension scaling factors for x/y to better align loss with metric space.

        - none: (1, 1) (original behavior)
        - pc_range: scale proportional to pc_range (normalized by mean range to keep magnitude stable)
        """
        if flow_coord_scaling in (None, 'none'):
            return (1.0, 1.0)
        if flow_coord_scaling != 'pc_range':
            raise ValueError(f'Unsupported flow_coord_scaling={flow_coord_scaling!r}, expected "none" or "pc_range".')
        range_x = float(pc_range[3] - pc_range[0])
        range_y = float(pc_range[4] - pc_range[1])
        mean_range = max((range_x + range_y) / 2.0, 1e-6)
        return (range_x / mean_range, range_y / mean_range)
    
    def init_weights(self):
        """初始化权重"""
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)
        
        bias_init = bias_init_with_prob(0.01)
        nn.init.constant_(self.cls_head[-1].bias, bias_init)
    
    @force_fp32(apply_to=('mlvl_feats', 'prev_bev'))
    def forward(self, mlvl_feats, img_metas, prev_bev=None, only_bev=False):
        """
        统一的forward接口 (CGNet风格)
        支持Transformer编码BEV和Query特征
        """
        if self.transformer is None:
            # 无Transformer，直接返回图像特征
            if isinstance(mlvl_feats, (list, tuple)):
                return mlvl_feats[0]
            return mlvl_feats
        
        # 使用Transformer编码
        bs = mlvl_feats[0].shape[0]
        dtype = mlvl_feats[0].dtype
        
        # Query embedding
        if self.query_embed_type == 'all_pts':
            object_query_embeds = self.query_embedding.weight.to(dtype)
        elif self.query_embed_type == 'instance_pts':
            # [num_ctrl_points, D*2] -> [1, num_ctrl_points, D*2]
            pts_embeds = self.pts_embedding.weight.unsqueeze(0)
            # [num_instances, D*2] -> [num_instances, 1, D*2]
            instance_embeds = self.instance_embedding.weight.unsqueeze(1)
            # 广播相加: [num_instances, num_ctrl_points, D*2]
            # 然后展平: [num_instances * num_ctrl_points, D*2]
            object_query_embeds = (pts_embeds + instance_embeds).flatten(0, 1).to(dtype)
        
        # BEV queries
        if self.bev_embedding is not None:
            bev_queries = self.bev_embedding.weight.to(dtype)
            bev_mask = torch.zeros((bs, self.bev_h, self.bev_w), device=bev_queries.device).to(dtype)
            bev_pos = self.positional_encoding(bev_mask).to(dtype)
        else:
            bev_queries = None
            bev_mask = None
            bev_pos = None
        
        if only_bev:
            return self.transformer.get_bev_features(
                mlvl_feats,
                None,  # lidar_feat
                bev_queries,
                self.bev_h,
                self.bev_w,
                grid_length=(self.real_h / self.bev_h, self.real_w / self.bev_w),
                bev_pos=bev_pos,
                img_metas=img_metas,
                prev_bev=prev_bev,
            )
        else:
            # 完整Transformer: BEV Encoder + Decoder
            outputs = self.transformer(
                mlvl_feats,
                None,  # lidar_feat
                bev_queries,
                object_query_embeds,
                self.bev_h,
                self.bev_w,
                grid_length=(self.real_h / self.bev_h, self.real_w / self.bev_w),
                bev_pos=bev_pos,
                img_metas=img_metas,
                prev_bev=prev_bev
            )
            
            bev_embed, hs, init_reference, inter_references, kp_bev_preds = outputs
            # hs: [num_decoder_layers, bs, num_query, embed_dims]
            # Standardize BEV layout: transformer returns [H*W, bs, C]; downstream expects [bs, H*W, C].
            if (bev_embed.dim() == 3 and bev_embed.shape[0] == self.bev_h * self.bev_w
                    and bev_embed.shape[1] == bs):
                bev_embed = bev_embed.permute(1, 0, 2).contiguous()

            debug_enabled = os.environ.get('CGNET_DEBUG_FLOW_SHAPES', '').lower() in ('1', 'true', 'yes', 'y')
            is_main_process = os.environ.get('RANK', '0') in ('0', '-1')
            if debug_enabled and is_main_process:
                if not getattr(self, '_debug_forward_shapes_printed', False):
                    self._debug_forward_shapes_printed = True
                    mlvl0_shape = tuple(mlvl_feats[0].shape) if isinstance(mlvl_feats, (list, tuple)) else tuple(mlvl_feats.shape)
                    print(
                        f'[FlowCenterlineHead.forward] mlvl_feats[0]={mlvl0_shape} '
                        f'bev_embed={tuple(bev_embed.shape)} hs={tuple(hs.shape)} '
                        f'bev_h={self.bev_h} bev_w={self.bev_w}',
                        flush=True,
                    )
                    if bev_embed.dim() == 3 and bev_embed.shape[1] == self.bev_h * self.bev_w:
                        print(
                            '[FlowCenterlineHead.forward] NOTE: bev_embed is [B, H*W, C].',
                            flush=True,
                        )
            
            return bev_embed, hs
    
    def forward_train(self, bev_features, query_feat, gt_bboxes_list, 
                     gt_labels_list, img_metas, gt_topology=None):
        """
        训练前向传播
        
        Args:
            bev_features: [B, C, H, W] BEV特征
            query_feat: [B, N, D] Query特征 (来自decoder)
            gt_bboxes_list: GT中心线列表
            gt_labels_list: GT标签列表
            img_metas: 图像元信息
            gt_topology: GT拓扑 (可选)
        """
        B = len(gt_bboxes_list)
        device = bev_features.device
        
        # Debug: print shapes to verify BEV/query layout (set env CGNET_DEBUG_FLOW_SHAPES=1)
        debug_enabled = os.environ.get('CGNET_DEBUG_FLOW_SHAPES', '').lower() in ('1', 'true', 'yes', 'y')
        is_main_process = os.environ.get('RANK', '0') in ('0', '-1')
        if debug_enabled and is_main_process:
            if not getattr(self, '_debug_forward_train_shapes_printed', False):
                self._debug_forward_train_shapes_printed = True
                print(
                    f'[FlowCenterlineHead] bev_features={tuple(bev_features.shape)} '
                    f'query_feat={tuple(query_feat.shape)} B(gt)={B}',
                    flush=True,
                )
                if bev_features.dim() == 3 and bev_features.shape[0] != B and bev_features.shape[1] == B:
                    print(
                        '[FlowCenterlineHead] WARNING: bev_features appears to be [H*W, B, C]; '
                        'some modules expect [B, H*W, C] or [B, C, H, W].',
                        flush=True,
                    )

        # Standardize BEV layout: allow either [B, H*W, C] or [H*W, B, C].
        if (bev_features.dim() == 3 and bev_features.shape[0] == self.bev_h * self.bev_w
                and bev_features.shape[1] == B):
            bev_features = bev_features.permute(1, 0, 2).contiguous()
        
        # ===== 处理 query_feat 结构 =====
        # instance_pts模式: [B, N, P, D] - 每个控制点有独立特征
        # all_pts模式: [B, N, D] - 每条线共享特征
        if query_feat.dim() == 4:
            # [B, N, P, D] -> 提取 per-line 特征用于分类和拓扑
            B, N, P, D = query_feat.shape
            query_feat_per_ctrl = query_feat  # 用于 Flow Matching
            query_feat_per_line = query_feat.mean(dim=2)  # [B, N, D] 用于分类/拓扑
        else:
            # [B, N, D]
            B, N, D = query_feat.shape
            query_feat_per_ctrl = query_feat  # velocity_net 会自动 expand
            query_feat_per_line = query_feat

        # For points-mode we must pass per-line query features (dim=3) to the velocity net.
        if self.coord_mode == 'ctrl_points':
            query_feat_for_flow = query_feat_per_ctrl
        else:
            # Prefer per-point query features when available ([B, N, P, D]).
            query_feat_for_flow = query_feat_per_ctrl if query_feat_per_ctrl.dim() == 4 else query_feat_per_line
        
        # 1. 准备GT (使用Hungarian匹配，传入BEV特征)
        gt_coords, gt_adj, pos_mask = self.prepare_gt(
            gt_bboxes_list, gt_labels_list, gt_topology, device, 
            query_feat=query_feat_per_line, bev_features=bev_features
        )
        
        # 2. 存在性预测 (使用 per-line 特征)
        cls_logits = self.cls_head(query_feat_per_line)  # [B, N, 1]
        
        # NaN 检查: 如果输入特征已经 NaN，跳过本次训练返回 0 loss
        if torch.isnan(query_feat_per_line).any() or torch.isnan(bev_features).any():
            zero_loss = torch.tensor(0.0, device=device, requires_grad=True)
            return {
                'loss_flow': zero_loss, 'loss_topo': zero_loss,
                'loss_cls': zero_loss, 'loss_kp': zero_loss,
            }
        
        # 3. Flow Matching损失 (使用动态位置先验，从query特征预测)
        query_feat_for_prior = query_feat_per_ctrl if query_feat_per_ctrl.dim() == 4 else query_feat_per_line
        x0_prior = self.predict_x0_prior(query_feat_for_prior)  # [B, N, P, 2]
        loss_flow = self.flow_loss(
            self.velocity_net,
            gt_coords,
            query_feat_for_flow,
            bev_features,
            pos_mask,
            x0_prior=x0_prior
        )
        
        # 4. 拓扑损失 - 使用原始CGNet的GNN+GRU+TopologyHead (多层迭代)
        with torch.no_grad():
            pred_coords = self.sample(query_feat_for_flow, bev_features)
        
        # 构建初始邻接矩阵 (基于端点距离)
        adj = self.build_init_adj(pred_coords, pos_mask)
        
        # CGNet风格: 多层GNN -> GRU -> TopologyHead 迭代 (使用 per-line 特征)
        vertex_feat = query_feat_per_line
        hidden = None
        topo_logits_list = []
        
        for layer_idx in range(self.num_gnn_layers):
            # GNN
            vertex_feat_permuted = vertex_feat.permute(1, 0, 2)  # [N, B, D]
            vertex_feat_permuted = self.vertex_gnn(vertex_feat_permuted, adj)
            vertex_feat = vertex_feat_permuted.permute(1, 0, 2)  # [B, N, D]
            
            # GRU
            hidden = self.vertex_gru(vertex_feat, hidden)
            
            # TopologyHead (每层都预测)
            topo_logits = self.topo_heads_multi[layer_idx](hidden)
            topo_logits_list.append(topo_logits)
            
            # 更新邻接矩阵用于下一层
            adj = torch.sigmoid(topo_logits)
        
        # 多层监督损失
        loss_topo = 0
        for lvl, logits in enumerate(topo_logits_list):
            weight = 1.0 if lvl == len(topo_logits_list) - 1 else 0.5
            loss_topo = loss_topo + weight * self.topo_loss(logits, gt_adj, pos_mask)
        loss_topo = loss_topo / (len(topo_logits_list) * 0.5 + 0.5)
        
        # 5. 分类损失
        loss_cls = self.cls_loss(cls_logits, pos_mask)
        
        # 6. JAQ损失 (Junction-Aware Query)
        loss_kp = torch.tensor(0.0, device=device)
        if self.use_jaq:
            # 预测keypoint热图
            if bev_features.dim() == 4:
                kp_feat = self.kp_decoder(bev_features)
                kp_pred = self.kp_proj(kp_feat).squeeze(1)  # [B, H, W]
            else:
                # BEV features是flatten的，需要reshape
                bev_2d = bev_features.permute(0, 2, 1).reshape(B, -1, self.bev_h, self.bev_w)
                kp_feat = self.kp_decoder(bev_2d)
                kp_pred = self.kp_proj(kp_feat).squeeze(1)  # [B, H, W]
            
            # 生成GT热图
            gt_kp_list = [self.get_bev_keypoint(gt_bboxes).to(device) for gt_bboxes in gt_bboxes_list]
            gt_kp = torch.stack(gt_kp_list)  # [B, H, W]
            
            # 计算损失 (Modified Focal Loss)
            loss_kp = self._neg_loss(kp_pred, gt_kp, weights=2) * self.loss_kp_weight
        
        # 7. 汇总损失
        losses = {
            'loss_flow': loss_flow * self.loss_flow_weight,
            'loss_topo': loss_topo * self.loss_topo_weight,
            'loss_cls': loss_cls,
            'loss_kp': loss_kp,
        }
        
        # 7. GRPO (在后期epoch启用)
        if self.use_grpo and self.current_epoch >= self.grpo_start_epoch:
            cls_scores = cls_logits.sigmoid().squeeze(-1)
            
            # 定义拓扑前向函数 (多层GNN迭代)
            # 简化版 GRPO (DIVER 风格)
            loss_grpo, grpo_log = self.grpo(
                sample_fn=lambda q, b: self.sample(q, b),
                flow_loss_fn=self.flow_loss,
                velocity_net=self.velocity_net,
                query_feat=query_feat_for_flow,
                bev_feat=bev_features,
                gt_coords=gt_coords,
                gt_adj=gt_adj,
                gt_mask=pos_mask,
                x0_prior=x0_prior,
                cls_scores=cls_scores,
            )
            
            losses['loss_grpo'] = loss_grpo * 0.1
            
            # 添加GRPO日志
            for k, v in grpo_log.items():
                losses[k] = torch.tensor(v, device=device)
        
        return losses
    
    def forward_test(self, bev_features, query_feat, img_metas):
        """
        测试/推理前向传播
        """
        B = bev_features.shape[0]

        # Standardize BEV layout: allow either [B, H*W, C] or [H*W, B, C].
        if (bev_features.dim() == 3 and bev_features.shape[0] == self.bev_h * self.bev_w
                and bev_features.shape[1] == B):
            bev_features = bev_features.permute(1, 0, 2).contiguous()
        
        # 处理 query_feat 结构
        if query_feat.dim() == 4:
            # [B, N, P, D] -> 提取 per-line 特征
            query_feat_per_ctrl = query_feat
            query_feat_per_line = query_feat.mean(dim=2)  # [B, N, D]
        else:
            query_feat_per_ctrl = query_feat
            query_feat_per_line = query_feat
        
        # 1. 采样生成坐标
        if self.coord_mode == 'ctrl_points':
            query_feat_for_flow = query_feat_per_ctrl
        else:
            query_feat_for_flow = query_feat_per_ctrl if query_feat_per_ctrl.dim() == 4 else query_feat_per_line
        pred_coords = self.sample(query_feat_for_flow, bev_features)
        
        # 2. 存在性预测 (使用 per-line 特征)
        cls_logits = self.cls_head(query_feat_per_line)
        cls_scores = cls_logits.sigmoid().squeeze(-1)  # [B, N]
        
        # 3. 拓扑预测 - 使用原始CGNet的GNN+GRU+TopologyHead (多层迭代)
        adj = self.build_init_adj(pred_coords, cls_scores > 0.3)
        vertex_feat = query_feat_per_line
        hidden = None
        
        for layer_idx in range(self.num_gnn_layers):
            vertex_feat_permuted = vertex_feat.permute(1, 0, 2)
            vertex_feat_permuted = self.vertex_gnn(vertex_feat_permuted, adj)
            vertex_feat = vertex_feat_permuted.permute(1, 0, 2)
            hidden = self.vertex_gru(vertex_feat, hidden)
            topo_logits = self.topo_heads_multi[layer_idx](hidden)
            adj = torch.sigmoid(topo_logits)  # 返回 sigmoid后的结果
        
        topo_probs = adj  # 最后一层的结果
        
        # 4. 后处理
        results = self.post_process(pred_coords, cls_scores, topo_probs, img_metas)
        
        return results
    
    def _sigmoid_range(self, x):
        return self.coord_min + (self.coord_max - self.coord_min) * torch.sigmoid(x)

    def predict_x0_prior(self, query_feat):
        """
        从query特征预测初始位置先验
        
        Args:
            query_feat: [B, N, D] 或 [B, N, P, D]
        
        Returns:
            x0_prior: [B, N, P, 2] 初始位置 (归一化到[0,1])
        """
        if query_feat.dim() == 4:
            B, N, P, D = query_feat.shape
            query_feat_points = query_feat
            query_feat_per_line = query_feat.mean(dim=2)
        else:
            B, N, D = query_feat.shape
            P = self.flow_num_points
            query_feat_per_line = query_feat
            query_feat_points = query_feat_per_line.unsqueeze(2).expand(-1, -1, P, -1)

        debug_enabled = os.environ.get('CGNET_DEBUG_FLOW_SHAPES', '').lower() in ('1', 'true', 'yes', 'y')
        is_main_process = os.environ.get('RANK', '0') in ('0', '-1')

        # 预测并reshape
        x0_flat = self.x0_predictor(query_feat_per_line)  # [B, N, P*2]
        x0_ctrl_raw = x0_flat.view(B, N, self.num_ctrl_points, 2)
        # 用受限sigmoid映射到 [coord_min, coord_max]，避免边界饱和
        x0_ctrl = self._sigmoid_range(x0_ctrl_raw)

        if self.coord_mode == 'ctrl_points':
            x0_prior = x0_ctrl
        else:
            if self.x0_prior_type == 'bezier':
                x0_prior = bezier_interpolate(x0_ctrl, num_points=self.flow_num_points)
            elif self.x0_prior_type == 'points':
                x0_pts_raw = self.x0_points_predictor(query_feat_points)
                x0_prior = self._sigmoid_range(x0_pts_raw)
            else:
                # bezier_residual
                base = bezier_interpolate(x0_ctrl, num_points=self.flow_num_points)
                residual = self.x0_residual_predictor(query_feat_points)
                residual = torch.tanh(residual) * float(self.x0_residual_scale)
                x0_prior = torch.clamp(base + residual, self.coord_min, self.coord_max)

        if debug_enabled and is_main_process:
            if not getattr(self, '_debug_x0_prior_printed', False):
                self._debug_x0_prior_printed = True
                sat = ((x0_prior < 0.05) | (x0_prior > 0.95)).float().mean().item()
                print(
                    f'[FlowCenterlineHead] x0_prior stats: '
                    f'min={x0_prior.min().item():.4f} max={x0_prior.max().item():.4f} '
                    f'mean={x0_prior.mean().item():.4f} sat(<0.05|>0.95)={sat:.3f} '
                    f'coord_mode={self.coord_mode} x0_prior_type={self.x0_prior_type}',
                    flush=True,
                )
        return x0_prior
    
    @torch.no_grad()
    def sample(self, query_feat, bev_features, num_steps=None):
        """
        Flow Matching采样
        
        Args:
            query_feat: [B, N, D] 或 [B, N, P, D]
        """
        if num_steps is None:
            num_steps = self.num_sampling_steps
        
        # 支持两种输入格式
        if query_feat.dim() == 4:
            B, N, P_feat, D = query_feat.shape
            if P_feat != self.flow_num_points:
                raise ValueError(
                    f'query_feat has P={P_feat} but coord_mode={self.coord_mode!r} requires '
                    f'P={self.flow_num_points}; pass per-line features [B,N,D] for coord_mode="points".'
                )
            query_feat_per_line = query_feat.mean(dim=2)  # [B, N, D]
        else:
            B, N, D = query_feat.shape
            query_feat_per_line = query_feat
        device = query_feat.device

        # Standardize BEV layout: allow either [B, H*W, C] or [H*W, B, C].
        if (bev_features.dim() == 3 and bev_features.shape[0] == self.bev_h * self.bev_w
                and bev_features.shape[1] == B):
            bev_features = bev_features.permute(1, 0, 2).contiguous()
        
        def velocity_fn(x, t):
            return self.velocity_net(x, t, query_feat, bev_features)
        
        shape = (B, N, self.flow_num_points, 2)
        
        # 使用动态位置先验作为起点 (从query特征预测)
        x0_prior = self.predict_x0_prior(query_feat if query_feat.dim() == 4 else query_feat_per_line)
        
        coords = self.flow_module.euler_sample(
            velocity_fn, shape, device, num_steps, x0_prior=x0_prior
        )
        
        # 确保在[coord_min, coord_max]范围内 (用clamp保持分布)
        coords = torch.clamp(coords, self.coord_min, self.coord_max)
        
        return coords
    
    def prepare_gt(self, gt_bboxes_list, gt_labels_list, gt_topology, device, query_feat=None, bev_features=None):
        """
        准备GT数据 (使用Hungarian匹配)
        
        Args:
            query_feat: [B, N, D] 可选，用于Hungarian匹配
            bev_features: [B, C, H, W] 可选，用于Hungarian匹配
        
        Returns:
            gt_coords: [B, N, P, 2] 归一化坐标
            gt_adj: [B, N, N] 邻接矩阵
            pos_mask: [B, N] 有效mask
        """
        B = len(gt_bboxes_list)
        N = self.num_instances  # 线的数量 (不是总query数)
        P = self.flow_num_points
        
        gt_coords_list = []
        gt_adj_list = []
        pos_mask_list = []
        
        # 先收集所有GT
        all_gt_ctrl = []
        all_gt_labels = []
        for b, (gt_bboxes, gt_labels) in enumerate(zip(gt_bboxes_list, gt_labels_list)):
            if hasattr(gt_bboxes, 'instance_list'):
                centerlines = gt_bboxes.instance_list
            else:
                centerlines = gt_bboxes
            
            seq_points = []
            for line in centerlines:
                if isinstance(line, torch.Tensor):
                    line = line.cpu().numpy()
                if self.coord_mode == 'ctrl_points':
                    seq = fit_bezier(line, n_control=self.num_ctrl_points)
                else:
                    seq = resample_polyline(line, num_points=P)
                seq_points.append(seq)
            
            if len(seq_points) > 0:
                gt_seq = torch.from_numpy(np.stack(seq_points)).float().to(device)
                gt_seq_norm = normalize_coords(gt_seq, self.pc_range)
            else:
                gt_seq_norm = torch.zeros(0, P, 2, device=device)
            
            all_gt_ctrl.append(gt_seq_norm)
            all_gt_labels.append(torch.zeros(len(seq_points), dtype=torch.long, device=device))
        
        # Hungarian匹配 (如果提供了query_feat和bev_features)
        # 改进: 逐样本判断是否匹配，而非要求整个batch都有GT
        indices = [None] * B  # 每个样本独立的匹配结果
        
        if query_feat is not None and bev_features is not None and self.training:
            # 检查batch大小一致性
            B_query = query_feat.shape[0]
            B_gt = len(all_gt_ctrl)
            assert B_query == B_gt, f"Batch size mismatch: query_feat has {B_query}, gt has {B_gt}"
            
            # 检查哪些样本有GT
            has_gt = [len(gt) > 0 for gt in all_gt_ctrl]
            
            if any(has_gt):
                # 使用当前query预测进行匹配
                with torch.no_grad():
                    # Deterministic matching target:
                    # avoid adding sampling noise into Hungarian assignment, which would make assignments unstable.
                    pred_coords = self.predict_x0_prior(query_feat)
                    pred_logits = self.cls_head(query_feat)
                
                # 准备GT用于匹配 (处理M>N的情况)
                padded_gt_ctrl = []
                padded_gt_labels = []
                for gt_ctrl, gt_label in zip(all_gt_ctrl, all_gt_labels):
                    M = gt_ctrl.shape[0]
                    if M > N:
                        gt_ctrl = gt_ctrl[:N]
                        gt_label = gt_label[:N]
                        M = N
                    # Padding到N (无GT的样本padding全-1)
                    if M > 0:
                        padded_ctrl = F.pad(gt_ctrl, (0, 0, 0, 0, 0, N - M))
                        padded_label = F.pad(gt_label, (0, N - M), value=-1)
                    else:
                        padded_ctrl = torch.zeros(N, P, 2, device=device)
                        padded_label = torch.full((N,), -1, dtype=torch.long, device=device)
                    padded_gt_ctrl.append(padded_ctrl)
                    padded_gt_labels.append(padded_label)
                
                # 执行匹配 (matcher内部会处理空GT的情况，返回空匹配)
                indices = self.matcher(
                    pred_coords, pred_logits,
                    torch.stack(padded_gt_ctrl),
                    torch.stack(padded_gt_labels)
                )
        
        # 根据匹配结果填充GT
        for b in range(B):
            gt_ctrl_norm = all_gt_ctrl[b]
            M = gt_ctrl_norm.shape[0]
            
            gt_coords = torch.zeros(N, P, 2, device=device)
            pos_mask = torch.zeros(N, dtype=torch.bool, device=device)
            
            if M > 0:
                # 检查当前样本是否有有效匹配结果
                has_valid_match = (indices[b] is not None and 
                                   len(indices[b][0]) > 0)
                
                if has_valid_match:
                    # 使用匹配结果
                    row_ind, col_ind = indices[b]
                    gt_coords[row_ind] = gt_ctrl_norm[col_ind]
                    pos_mask[row_ind] = True
                else:
                    # 直接填充 (如果 M > N，截断)
                    M_use = min(M, N)
                    gt_coords[:M_use] = gt_ctrl_norm[:M_use]
                    pos_mask[:M_use] = True
                
                # GT拓扑
                gt_bboxes = gt_bboxes_list[b]
                if gt_topology is not None and hasattr(gt_bboxes, 'adj_matrix'):
                    adj = gt_bboxes.adj_matrix
                    if isinstance(adj, np.ndarray):
                        adj = torch.from_numpy(adj).float().to(device)
                    gt_adj = torch.zeros(N, N, device=device)
                    if has_valid_match:
                        # 重新映射拓扑
                        row_ind, col_ind = indices[b]
                        for i, ri in enumerate(row_ind):
                            for j, rj in enumerate(row_ind):
                                if col_ind[i] < adj.shape[0] and col_ind[j] < adj.shape[1]:
                                    gt_adj[ri, rj] = adj[col_ind[i], col_ind[j]]
                    else:
                        M_adj = min(M, N, adj.shape[0], adj.shape[1])
                        gt_adj[:M_adj, :M_adj] = adj[:M_adj, :M_adj]
                else:
                    # 传入截断后的coords (M_use已在上面计算)
                    M_use = min(M, N)
                    gt_adj = self.generate_topology_gt(gt_coords[pos_mask][:M_use], pos_mask, device)
            else:
                gt_adj = torch.zeros(N, N, device=device)
            
            gt_coords_list.append(gt_coords)
            gt_adj_list.append(gt_adj)
            pos_mask_list.append(pos_mask)
        
        gt_coords = torch.stack(gt_coords_list)
        gt_adj = torch.stack(gt_adj_list)
        pos_mask = torch.stack(pos_mask_list)
        
        return gt_coords, gt_adj, pos_mask
    
    def generate_topology_gt(self, coords, mask, device, threshold=2.0):
        """
        基于端点距离生成拓扑GT
        
        Args:
            coords: [M, P, 2] M条有效线的控制点
            mask: [N] 全局mask (N=num_queries)
            device: torch.device
        
        Returns:
            adj: [N, N] 完整的邻接矩阵
        """
        N = self.num_instances  # 线的数量 (不是总query数)
        M = coords.shape[0]  # 实际GT数量
        
        # 反归一化
        coords_denorm = denormalize_coords(coords, self.pc_range)
        
        # 端点
        start_pts = coords_denorm[:, 0, :]   # [M, 2]
        end_pts = coords_denorm[:, -1, :]    # [M, 2]
        
        # i的终点 -> j的起点
        dist = torch.cdist(end_pts, start_pts)  # [M, M]
        
        adj_m = (dist < threshold).float()
        adj_m.fill_diagonal_(0)
        
        # 扩展到[N, N]
        adj = torch.zeros(N, N, device=device)
        # 如果 M > N，截断；如果 M <= N，正常填充
        if mask is not None:
            valid_idx = torch.where(mask)[0]
            M_use = min(M, valid_idx.numel(), N)
            if M_use > 0:
                valid_idx = valid_idx[:M_use]
                adj_m_use = adj_m[:M_use, :M_use]
                adj[valid_idx[:, None], valid_idx[None, :]] = adj_m_use
        else:
            M_use = min(M, N)
            adj[:M_use, :M_use] = adj_m[:M_use, :M_use]
        
        return adj
    
    def build_init_adj(self, coords, mask, threshold=2.0):
        """
        构建初始邻接矩阵 (用于GNN输入)
        基于端点距离
        """
        B, N = coords.shape[:2]
        device = coords.device
        
        # 反归一化
        coords_denorm = denormalize_coords(coords, self.pc_range)
        
        # 端点
        start_pts = coords_denorm[:, :, 0, :]   # [B, N, 2]
        end_pts = coords_denorm[:, :, -1, :]    # [B, N, 2]
        
        # i的终点 -> j的起点
        dist = torch.cdist(end_pts, start_pts)  # [B, N, N]
        
        init_adj = (dist < threshold).float()
        
        # 只在有效位置
        if mask is not None:
            mask_2d = mask.unsqueeze(-1) & mask.unsqueeze(-2)
            init_adj = init_adj * mask_2d.float()
        
        # 去除自环
        eye = torch.eye(N, device=device).unsqueeze(0)
        init_adj = init_adj * (1 - eye)
        
        return init_adj
    
    def cls_loss(self, cls_logits, pos_mask):
        """分类损失"""
        B, N, _ = cls_logits.shape
        
        # 目标: 前景=0, 背景=num_classes
        target = torch.full((B, N), self.num_classes, device=cls_logits.device, dtype=torch.long)
        target[pos_mask] = 0
        
        weights = torch.ones(B, N, device=cls_logits.device)
        
        loss = self.loss_cls_fn(
            cls_logits.view(B * N, -1),
            target.view(B * N),
            weights.view(B * N),
            avg_factor=max(pos_mask.sum().item(), 1),
        )
        
        return loss
    
    def topo_loss(self, topo_logits, gt_adj, pos_mask):
        """拓扑损失 (只在有效位置)"""
        B, N, _ = topo_logits.shape
        
        # 只在有效位置计算
        mask_2d = pos_mask.unsqueeze(-1) & pos_mask.unsqueeze(-2)  # [B, N, N]
        
        loss = F.binary_cross_entropy_with_logits(
            topo_logits, gt_adj, reduction='none'
        )
        
        loss = (loss * mask_2d.float()).sum() / (mask_2d.sum() + 1e-6)
        
        return loss
    
    def get_bev_keypoint(self, lines):
        """
        从GT中心线提取路口点生成BEV热图 (CGNet风格)
        
        Args:
            lines: GT数据 (包含instance_list或key_points)
        
        Returns:
            bev_keypoint_map: torch.Tensor, shape (H, W)
        """
        bev_keypoint_map = np.zeros((self.bev_h, self.bev_w))
        
        # 获取关键点
        if hasattr(lines, 'key_points'):
            keypoints = lines.key_points
        elif hasattr(lines, 'instance_list'):
            # 从线提取端点
            keypoints = []
            for instance in lines.instance_list:
                if hasattr(instance, 'coords'):
                    coords = instance.coords
                else:
                    coords = instance
                if isinstance(coords, torch.Tensor):
                    coords = coords.cpu().numpy()
                if len(coords) > 0:
                    keypoints.append(coords[0])   # 起点
                    keypoints.append(coords[-1])  # 终点
        else:
            return torch.tensor(bev_keypoint_map, dtype=torch.float32)
        
        # 映射到BEV坐标
        for key in keypoints:
            if isinstance(key, torch.Tensor):
                key = key.cpu().numpy()
            key = np.array(key)
            
            if len(key) >= 2:
                # x -> col, y -> row
                col = (key[0] - self.pc_range[0]) / (self.pc_range[3] - self.pc_range[0]) * self.bev_w
                row = (key[1] - self.pc_range[1]) / (self.pc_range[4] - self.pc_range[1]) * self.bev_h
                
                col = int(np.clip(col, 0, self.bev_w - 1))
                row = int(np.clip(row, 0, self.bev_h - 1))
                
                bev_keypoint_map[row, col] = 1
        
        # 膨胀热图
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (self.dilate_radius, self.dilate_radius))
        bev_keypoint_map = cv2.dilate(bev_keypoint_map, kernel)
        
        return torch.tensor(bev_keypoint_map, dtype=torch.float32)
    
    def _neg_loss(self, pred, gt, weights=None):
        """
        Modified Focal Loss (CornerNet style)
        用于keypoint热图监督
        
        Args:
            pred: [B, H, W] 预测热图 (已经sigmoid)
            gt: [B, H, W] GT热图
            weights: 正样本权重
        
        Returns:
            loss: 标量损失
        """
        pos_inds = gt.eq(1).float()
        neg_inds = gt.lt(1).float()
        
        neg_weights = torch.pow(1 - gt, 4)
        
        loss = 0
        eps = 1e-6
        
        pos_loss = torch.log(pred + eps) * torch.pow(1 - pred, 2) * pos_inds
        neg_loss = torch.log(1 - pred + eps) * torch.pow(pred, 2) * neg_weights * neg_inds
        
        num_pos = pos_inds.float().sum()
        neg_loss = neg_loss.sum()
        
        if weights is not None:
            pos_loss = (pos_loss * weights).sum()
        else:
            pos_loss = pos_loss.sum()
        
        if num_pos == 0:
            loss = loss - neg_loss
        else:
            loss = loss - (pos_loss + neg_loss) / num_pos
        
        return loss
    
    def post_process(self, ctrl_points, cls_scores, topo_probs, img_metas):
        """后处理"""
        B = ctrl_points.shape[0]
        results = []
        
        for b in range(B):
            scores = cls_scores[b]  # [N]
            mask = scores > 0.3
            
            # 反归一化
            ctrl_denorm = denormalize_coords(ctrl_points[b][mask], self.pc_range)
            
            # 得到点序列 (统一输出 num_pts_per_line 点)
            if ctrl_denorm.shape[0] > 0:
                if self.coord_mode == 'ctrl_points':
                    points = bezier_interpolate(ctrl_denorm, num_points=self.num_pts_per_line)
                else:
                    points = ctrl_denorm
            else:
                points = torch.zeros(0, self.num_pts_per_line, 2, device=ctrl_points.device)
            
            num_lines = mask.sum().item()
            
            result = {
                'line': points.cpu(),
                'line_scores': scores[mask].cpu(),
                'line_labels': torch.zeros(num_lines, dtype=torch.long),
                'centerlines': points.cpu().numpy(),
                'scores': scores[mask].cpu().numpy(),
                'ctrl_points': ctrl_denorm.cpu().numpy(),
                'coord_mode': self.coord_mode,
            }
            
            # 拓扑
            if num_lines > 0:
                topo_masked = topo_probs[b][mask][:, mask]
                result['adj_matrix'] = (topo_masked > 0.5).cpu().numpy()
                result['topology_scores'] = topo_masked.cpu().numpy()
            else:
                result['adj_matrix'] = np.zeros((0, 0), dtype=np.float32)
            
            results.append(result)
        
        return results
    
    @force_fp32(apply_to=('preds_dicts'))
    def get_bboxes(self, preds_dicts):
        """
        CGNet风格的后处理接口
        使用bbox_coder解码预测结果
        """
        if self.bbox_coder is not None:
            preds_dicts = self.bbox_coder.decode(preds_dicts)
        
        num_samples = len(preds_dicts)
        ret_list = []
        
        for i in range(num_samples):
            preds = preds_dicts[i]
            line_scores = preds.get('line_scores', preds.get('scores', None))
            line_labels = preds.get('line_labels', torch.zeros(0, dtype=torch.long))
            line = preds.get('line', preds.get('centerlines', None))
            pts_scores = preds.get('pts_scores', line_scores)
            pts_labels = preds.get('pts_labels', line_labels)
            pts = preds.get('pts', line)
            graphs = preds.get('graph', None)
            adj_matrix = preds.get('adj_matrix', None)
            ret_list.append([line_scores, line_labels, line,
                            pts_scores, pts_labels, pts, graphs, adj_matrix])
        
        return ret_list


# TopologyHead已移除，使用CGNet原版的AdvancedTopologyGNN
